import http from "http"; import crypto from "crypto"; import {WebSocketServer} from "ws";
const PORT=process.env.PORT||8080, rooms=new Map();
const html=`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><title>Traitors Online</title><style>
body{margin:0;background:#080b12;color:#eef2ff;font:16px system-ui;display:grid;place-items:center;min-height:100vh}.c{width:min(820px,92vw);background:#111827;padding:24px;border-radius:18px}input,button,select{padding:12px;margin:5px;border-radius:9px;background:#0b1220;color:white;border:1px solid #39465e}button{background:#4f46e5;border:0;font-weight:700;cursor:pointer}.row{display:flex;gap:8px}.hidden{display:none}.p{padding:9px;margin:5px 0;background:#192337;border-radius:8px}.dead{text-decoration:line-through;opacity:.5}#feed{height:170px;overflow:auto;background:#080c14;padding:10px;border-radius:10px;margin:12px 0}</style>
<div class=c id=menu><h1>TRAITORS ONLINE</h1><p>Use your group chat for discussion. No in-game meetings.</p><input id=n maxlength=16 placeholder="Your name"><div class=row><button onclick="create()">Create Room</button><button onclick="join()">Join Room</button></div><input id=code maxlength=6 placeholder="Room code"><p id=s>Connecting…</p></div>
<div class="c hidden" id=lobby><h2>Lobby <span id=rb></span></h2><p>Send the room code to your friends.</p><div id=lp></div><button id=start onclick="send('start')">Start Game</button></div>
<div class="c hidden" id=game><h2><span id=role>Role: ?</span></h2><div id=feed></div><button onclick="send('task')">Complete Task</button><div id=tb class=hidden><h3>Traitor</h3><select id=t></select><button onclick="send('eliminate',{target:t.value})">Eliminate</button></div><h3>Players</h3><div id=gp></div><button onclick="send('reset')">New Round</button></div>
<script>
let w,id,room;const $=x=>document.getElementById(x);function show(x){['menu','lobby','game'].forEach(y=>$(y).classList.toggle('hidden',y!=x))}function send(type,data={}){w?.send(JSON.stringify({type,...data}))}
function conn(){if(w?.readyState===1)return;w=new WebSocket((location.protocol==='https:'?'wss':'ws')+'://'+location.host);w.onopen=()=>s.textContent='Connected';w.onmessage=e=>h(JSON.parse(e.data))}
function create(){conn();setTimeout(()=>send('create',{name:($('n').value||'Player').slice(0,16)}),100)}function join(){conn();setTimeout(()=>send('join',{name:($('n').value||'Player').slice(0,16),code:$('code').value}),100)}
function log(x){let d=document.createElement('div');d.textContent=x;$('feed').appendChild(d)}function render(a,e){$(e).innerHTML=a.map(p=>'<div class="p '+(p.alive?'':'dead')+'">'+p.name+(p.host?' 👑':'')+(p.id===id?' (You)':'')+'</div>').join('');if(e==='gp')$('t').innerHTML=a.filter(p=>p.alive&&p.id!==id).map(p=>'<option value="'+p.id+'">'+p.name+'</option>').join('')}
function h(m){if(m.type==='hello')id=m.id;if(m.type==='error')sText(m.message);if(m.type==='room'||m.type==='lobby'){room=m.code;$('rb').textContent='Code: '+m.code;render(m.players,'lp');show('lobby')}if(m.type==='started'){show('game');$('role').textContent='Role: '+m.role;$('tb').classList.toggle('hidden',m.role!=='Traitor');render(m.players,'gp');log('Game started. Use your group chat for discussion.')}if(m.type==='state'){render(m.players,'gp');if(m.tasks!==undefined)log('Tasks completed: '+m.tasks)}if(m.type==='event')log(m.text);if(m.type==='ended')log(m.winner+' win!')}
conn();
</script>`;

function code(){let c;do c=crypto.randomBytes(3).toString("hex").toUpperCase();while(rooms.has(c));return c}
const send=(w,x)=>w.readyState===1&&w.send(JSON.stringify(x)), pub=r=>[...r.p.values()].map(x=>({id:x.id,name:x.name,alive:x.alive,host:x.id===r.host}));
const winner=r=>{let a=[...r.p.values()].filter(x=>x.alive),t=a.filter(x=>x.role==="Traitor").length,i=a.length-t,tasks=[...r.p.values()].reduce((n,x)=>n+x.tasks,0);return t===0||tasks>=r.p.size*3?"Innocents":t>=i?"Traitors":null};
const srv=http.createServer((q,res)=>{res.writeHead(200,{"content-type":"text/html"});res.end(q.url==="/health"?JSON.stringify({status:"ok"}):html)});
const ws=new WebSocketServer({server:srv});
ws.on("connection",sock=>{let x={id:crypto.randomUUID(),ws:sock,room:null,name:"Player",role:null,alive:true,tasks:0};send(sock,{type:"hello",id:x.id});
sock.on("message",raw=>{let m;try{m=JSON.parse(raw)}catch{return}let r=x.room&&rooms.get(x.room);
if(m.type==="create"){r={code:code(),host:x.id,started:false,p:new Map};x.room=r.code;x.name=String(m.name||"Player").slice(0,16);r.p.set(x.id,x);rooms.set(r.code,r);return send(sock,{type:"room",code:r.code,players:pub(r)})}
if(m.type==="join"){if(r)return; r=rooms.get(String(m.code||"").toUpperCase());if(!r)return send(sock,{type:"error",message:"Room not found"});if(r.started||r.p.size>=12)return send(sock,{type:"error",message:"Room unavailable"});x.room=r.code;x.name=String(m.name||"Player").slice(0,16);r.p.set(x.id,x);for(let z of r.p.values())send(z.ws,{type:"lobby",code:r.code,players:pub(r)});return}
if(!r)return send(sock,{type:"error",message:"Create or join a room first"});
if(m.type==="start"){if(x.id!==r.host)return; if(r.p.size<2)return send(sock,{type:"error",message:"Need 2+ players"});r.started=true;let a=[...r.p.values()];a.forEach(z=>{z.alive=true;z.tasks=0;z.role="Innocent"});a.sort(()=>Math.random()-.5).slice(0,Math.max(1,Math.floor(a.length/4))).forEach(z=>z.role="Traitor");a.forEach(z=>send(z.ws,{type:"started",role:z.role,players:pub(r)}))}
if(m.type==="task"&&r.started&&x.alive){if(x.tasks<3)x.tasks++;send(x.ws,{type:"state",players:pub(r),tasks:x.tasks});for(let z of r.p.values())if(z.id!==x.id)send(z.ws,{type:"state",players:pub(r)});for(let z of r.p.values())send(z.ws,{type:"event",text:x.name+" completed a task."});let w=winner(r);if(w){r.started=false;for(let z of r.p.values())send(z.ws,{type:"ended",winner:w})}}
if(m.type==="eliminate"&&r.started&&x.alive&&x.role==="Traitor"){let t=r.p.get(String(m.target));if(t?.alive&&t.id!==x.id){t.alive=false;for(let z of r.p.values())send(z.ws,{type:"state",players:pub(r)});for(let z of r.p.values())send(z.ws,{type:"event",text:t.name+" was eliminated."});let w=winner(r);if(w){r.started=false;for(let z of r.p.values())send(z.ws,{type:"ended",winner:w})}}}
if(m.type==="reset"&&x.id===r.host){r.started=false;for(let z of r.p.values()){z.role=null;z.alive=true;z.tasks=0}for(let z of r.p.values())send(z.ws,{type:"lobby",code:r.code,players:pub(r)})}
});
sock.on("close",()=>{let r=x.room&&rooms.get(x.room);if(!r)return;r.p.delete(x.id);if(r.host===x.id)r.host=r.p.keys().next().value;if(!r.p.size)rooms.delete(r.code);else for(let z of r.p.values())send(z.ws,{type:r.started?"state":"lobby",code:r.code,players:pub(r)})})});
srv.listen(PORT,()=>console.log("Traitors Online on "+PORT));
